/*
 *  ------------------------------------------------------------------------------------
 *
 *  GF Monitor project
 *
 *  Module:  gfmon-engine (gfmon-engine)
 *  File:    JSONBTest.java
 *  Created: 2017.12.24. 18:19:09
 *
 *  ------------------------------------------------------------------------------------
 */
package hu.btsoft.gfmon;

import org.junit.Test;

/**
 *
 * @author BT
 */
public class JSONBTest {

    private final String JSON_STR = "{\n"
            + "	\"message\": \"\",\n"
            + "	\"command\": \"module-monitoring-levels\",\n"
            + "	\"exit_code\": \"SUCCESS\",\n"
            + "	\"extraProperties\": {\n"
            + "		\"commands\": [],\n"
            + "		\"methods\": [{\n"
            + "				\"name\": \"GET\"\n"
            + "			}, {}, {\n"
            + "				\"messageParameters\": {\n"
            + "					\"cloud\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"cloudElasticity\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"cloudOrchestrator\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"cloudTenantManager\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"cloudVirtAssemblyService\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"connectorConnectionPool\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"connectorService\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"deployment\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"ejbContainer\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"httpService\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"jdbcConnectionPool\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"jersey\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"jmsService\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"jpa\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"jvm\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"orb\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"security\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"threadPool\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"transactionService\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"webContainer\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					},\n"
            + "					\"webServicesContainer\": {\n"
            + "						\"defaultValue\": \"OFF\",\n"
            + "						\"optional\": \"true\",\n"
            + "						\"type\": \"string\",\n"
            + "						\"key\": \"false\"\n"
            + "					}\n"
            + "				},\n"
            + "				\"name\": \"POST\"\n"
            + "			}\n"
            + "		],\n"
            + "		\"entity\": {\n"
            + "			\"cloud\": \"OFF\",\n"
            + "			\"cloudElasticity\": \"OFF\",\n"
            + "			\"cloudOrchestrator\": \"OFF\",\n"
            + "			\"cloudTenantManager\": \"OFF\",\n"
            + "			\"cloudVirtAssemblyService\": \"OFF\",\n"
            + "			\"connectorConnectionPool\": \"OFF\",\n"
            + "			\"connectorService\": \"OFF\",\n"
            + "			\"deployment\": \"OFF\",\n"
            + "			\"ejbContainer\": \"OFF\",\n"
            + "			\"httpService\": \"OFF\",\n"
            + "			\"jdbcConnectionPool\": \"OFF\",\n"
            + "			\"jersey\": \"OFF\",\n"
            + "			\"jmsService\": \"OFF\",\n"
            + "			\"jpa\": \"OFF\",\n"
            + "			\"jvm\": \"OFF\",\n"
            + "			\"orb\": \"OFF\",\n"
            + "			\"security\": \"OFF\",\n"
            + "			\"threadPool\": \"OFF\",\n"
            + "			\"transactionService\": \"OFF\",\n"
            + "			\"webContainer\": \"OFF\",\n"
            + "			\"webServicesContainer\": \"OFF\"\n"
            + "		},\n"
            + "		\"childResources\": {\n"
            + "			\"property\": \"http:\\/\\/localhost:4848\\/management\\/domain\\/configs\\/config\\/server-config\\/monitoring-service\\/module-monitoring-levels\\/property\"\n"
            + "		}\n"
            + "	}\n"
            + "}";

    @Test
    public void testStartTimer() throws Exception {
    }

}
